### PR TITLE
Two small tweaks

### PR DESCRIPTION
**Pull request by noelleleigh**
See commits for details.

### CODE REVIEW

**Comment by karolbelina** [comment]
@noelleleigh thanks for the pr! The orca change looks fantastic, not sure about the uxncle change tho, here's my reasoning:

We have two options: (1) keep outdated projects on the list, or (2) remove them. The first option doesn't need any further maintenance from us after the project is added to the list, but folks new to the community may be confused as to what is actively maintained and what isn't. If we wanted to remove outdated projects from the list (or probably mark them as outdated somehow), we would have to actively check every project on the list once in a while, which could be viable, but would have to be done to every single project no exceptions. Any thoughts @neauoire?

(by "outdated" i mean projects that are no longer compatible with latest version of the original uxn toolchain. Is Uxncle "outdated"? Not sure, it parses the code, it produces the binary. Is the binary fully compatible with uxnemu? I guess only its maintainer can decide)

My proposal for now:
- let's keep Uxncle on the list
- optionally we can change its link to https://git.openpunk.com/CPunch/Uxncle since that is its original repo
- ask @neauoire to decide if we want to mark outdated projects, and how, and what are the criteria for being outdated lol

**Comment by noelleleigh** [comment]
> If we wanted to remove outdated projects from the list (or probably mark them as outdated somehow), we would have to actively check every project on the list once in a while, which could be viable, but would have to be done to every single project no exceptions.

That's definitely a legit concern regarding ongoing maintenance of this list! I'm by no means married to my change, so I'm totally willing to go along with whatever the maintainers decide.

> [...] by "outdated" i mean projects that are no longer compatible with latest version of the original uxn toolchain.

Now that's an interesting point. Does/will the uxn toolchain ever have official release versions? Are new features being added or is the spec considered frozen at this point? Without clear versions to reference, indicating compatibility in a concise way would prove pretty challenging.

**Comment by karolbelina** [comment]
@noelleleigh 
> Does/will the uxn toolchain ever have official release versions?

Maybe in the future, right now the project is too small for anyone to care about versions

> Are new features being added or is the spec considered frozen at this point?

we had the INC and NIP breaking change not that long ago, the File device on varvara got some tweaks, and now there's been some (theoretically) breaking changes with the include syntax. The project is too early-stage and too organic at this point, it just kinda grows without the need for versions, so we shouldn't really pretend like there are any.

can i ask u to revert 82468ce3e54a167f09d100d8d9c31b86867ca552? i'll make sure to merge the pr asap ^^

Also thanks for the opportunity for the discussion, @makeworld-the-better-one suggested something similar in https://github.com/hundredrabbits/awesome-uxn/pull/2 too. If anyone wants to add something i think this is the place

**Comment by neauoire** [comment]
Hey :) Sorry for the delay, 

I don't know if we want to start monitoring activity on repos right now, uxn is so young that unmaintained uxn projects just means that it's a month or two behind? Which I think is a bit too aggressive. We might have versioning at some point, or maybe we'll decide that what we have now is enough, if we do, then we can start to filter what is not up to spec, in the meantime, everything is a work-in-progress I suppose, I think of the awesome-uxn list as a "list of ideas", stepping stones that people can use to explore some ideas.

It's a good idea to flag abandonware, but let's wait at least until uxn is a year old.

**Comment by noelleleigh** [comment]
> can i ask u to revert [82468ce](https://github.com/hundredrabbits/awesome-uxn/commit/82468ce3e54a167f09d100d8d9c31b86867ca552)? i'll make sure to merge the pr asap ^^

Done!

**Pull request merged**
